Neos:
  Neos:
    fusion:
      autoInclude:
        'Ttree.Map': TRUE

  Fusion:
    defaultContext:
      GeoPoint: 'Ttree\Map\Eel\Helper\GeoPointHelper'

Ttree:
  Map:
    apiKey:
      name: "API KEY"
    # Configure GoogleMaps Geocoder
    geocoder:
      locale: null
      region: null
      useSSL: false
      apiKey: null
    styles:
      default:
        name: "Default Styles"
        settings:
          -
            featureType: 'road.highway'
            elementType: 'geometry'
            stylers:
              -
                saturation: -80
              -
                lightness: -8
              -
                gamma: -1
          -
            featureType: 'road.arterial'
            elementType: 'geometry'
            stylers:
              -
                saturation: -80
              -
                lightness: -24
              -
                gamma: -1
          -
            featureType: 'road.road'
            elementType: 'geometry'
            stylers:
              -
                saturation: -80

